### ISSUE TITLE
Add support for defaultZ/defaultT

### ISSUE THREAD

**Issue by sbesson** [ome/omero-cli-render#16]
As noticed as part of the work on https://github.com/IDR/idr0044-mcdole-tardislightsheet/pull/4, the render plugin YML format does not support the OMERO `defaultZ/defaultT` values.

For some datasets being able to both retrieve and set these values would be extremely valuable. I assume this might be represented as new top-level keys in the YML/JSON format

**Comment by sbesson** [comment]
As we might converge towards a version 2 of the YML format (https://github.com/ome/omero-cli-render/pull/15#discussion_r248330683), we might as well use the occasion and decision how we are going to represent these concepts in the YML rendering files.

Immediate options coming to mind are  `z/defaultz/defaultZ` and `t/defaultt/defaultT`, depending on the compromise between short names, matching the OMERO names and keeping every key lowercase. An example would probably look as follows

```
---
version: 2
z: 5
t: 1
channels:
  1:
        color: "FF0000"
        label: "Red"
        start: 1
        end: 255
        active: True
```

/cc @dominikl
